version: '3'

services:
  frontend:
    build: ./frontend
    image: next-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
    command: bash -c "npm run dev"

  backend:
    build: ./backend
    image: django-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./backend/db:/code/db
    command: bash -c "python3 manage.py collectstatic --noinput --clear; gunicorn  -w 2 --bind :8000 app.wsgi --reload"

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
